version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres@2019"
    ports:
      - "5432:5432"
    volumes:
      - /home/eduardofg87/Dropbox/0002-eu/Tutorials/go/Go+PostreSQL/database:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fake@email.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin@2019"
    ports:
      - "8081:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge